### PR TITLE
Fix runtime error with `Update 9` versions

### LINKED ISSUE #14: Ballerina application fails when we use `zipkin` module with `Update 9` versions
**Description:**
Application fails with the following error when we use `zipkin` module with  Ballerina `Update 9` versions.

```
[2024-07-25 09:57:24,792] SEVERE {b7a.log.crash} - 'io.opentelemetry.api.metrics.LongValueObserverBuilder io.opentelemetry.api.metrics.Meter.longValueObserverBuilder(java.lang.String)' 
java.lang.NoSuchMethodError: 'io.opentelemetry.api.metrics.LongValueObserverBuilder io.opentelemetry.api.metrics.Meter.longValueObserverBuilder(java.lang.String)'
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:148)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:116)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:69)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:140)
        at io.ballerina.observe.trace.zipkin.ZipkinTracerProvider.initializeConfigurations(ZipkinTracerProvider.java:83)
        at ballerinax.zipkin.0.tracer_provider.externInitializeConfigurations(tracer_provider.bal:48)
        at ballerinax.zipkin.0.tracer_provider.init(tracer_provider.bal:43)
        at ballerinax.zipkin.0.$_init.$gen$&0046&0060init&0062(zipkin:1)
        at nipunal.zipkin_test.0.$_init.$moduleInit(zipkin_test)
        at nipunal.zipkin_test.0.$_init.$moduleExecute(zipkin_test)
        at nipunal.zipkin_test.0.$_init.$lambda$$moduleExecute$(zipkin_test)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

### LINKED ISSUE #16: Code coverage is not updated
**Description:**
Code coverage is not updated in https://app.codecov.io/gh/ballerina-platform/module-ballerinax-zipkin.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by NipunaMadhushan**
## Purpose
$subject

Fixes #14 
Fixes #16 

## Automation tests
- Unit tests
  > Code coverage information
- Integration tests
  > Details about the test cases and coverage

## Security checks
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: native/src/main/java/io/ballerina/observe/trace/zipkin/sampler/RateLimitingSampler.java [hunk 1]
```diff
@@ -4,42 +4,52 @@
...
+
 /**
- * This class is copied from https://github.com/open-telemetry/opentelemetry-java/blob/v1.0.0/sdk-extensions/
+ * This class is copied from https://github.com/open-telemetry/opentelemetry-java/blob/v1.32.0/sdk-extensions/
  * jaeger-remote-sampler/src/main/java/io/opentelemetry/sdk/extension/trace/jaeger/sampler/RateLimitingSampler.java.
  * This sampler uses a leaky bucket rate limiter to ensure that traces are sampled with a certain constant rate.
  */
 public class RateLimitingSampler implements Sampler {
     public static final String TYPE = "ratelimiting";
+    static final AttributeKey<String> SAMPLER_TYPE = stringKey("sampler.type");
```
Comment (keizer619) [inline native/src/main/java/io/ballerina/observe/trace/zipkin/sampler/RateLimitingSampler.java]: Any specific reason to use default visibility? 
Other constants are public or private?

Comment (NipunaMadhushan) [reply native/src/main/java/io/ballerina/observe/trace/zipkin/sampler/RateLimitingSampler.java]: No specific reason. I changed them to be private.

**Review by keizer619 — APPROVED** [review]
